#pragma once

#define BM_CAPTURE_PICTURE WM_USER+1
#define BM_PREVIEW_DBLCLK  WM_USER+2
#define BM_PREVIEW_FOCUS   WM_USER+3
#define BM_PREVIEW_UNFOCUS WM_USER+4
#define BM_CONFIRM_SETTING WM_USER+5
#define BM_FILE_END        WM_USER+6